<?php

declare(strict_types=1);

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ColorPalettesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $palettes = [
            // CLÁSICAS (Disponibles para todos los planes - min_plan_id: 1)
            [
                'name' => 'Clásico Azul',
                'slug' => 'clasico-azul',
                'primary_color' => '#0066CC',
                'secondary_color' => '#FFFFFF',
                'accent_color' => null,
                'background_color' => '#FFFFFF',
                'text_color' => '#000000',
                'min_plan_id' => 1,
                'category' => 'clasico',
                'created_at' => now(),
            ],
            [
                'name' => 'Calidez Naranja',
                'slug' => 'calidez-naranja',
                'primary_color' => '#FF6600',
                'secondary_color' => '#FFCC00',
                'accent_color' => null,
                'background_color' => '#FFFFFF',
                'text_color' => '#000000',
                'min_plan_id' => 1,
                'category' => 'clasico',
                'created_at' => now(),
            ],
            [
                'name' => 'Natural Verde',
                'slug' => 'natural-verde',
                'primary_color' => '#339933',
                'secondary_color' => '#663300',
                'accent_color' => null,
                'background_color' => '#FFFFFF',
                'text_color' => '#000000',
                'min_plan_id' => 1,
                'category' => 'clasico',
                'created_at' => now(),
            ],
            [
                'name' => 'Elegante Negro',
                'slug' => 'elegante-negro',
                'primary_color' => '#000000',
                'secondary_color' => '#FFD700',
                'accent_color' => null,
                'background_color' => '#FFFFFF',
                'text_color' => '#000000',
                'min_plan_id' => 1,
                'category' => 'clasico',
                'created_at' => now(),
            ],
            [
                'name' => 'Fresco Celeste',
                'slug' => 'fresco-celeste',
                'primary_color' => '#00BFFF',
                'secondary_color' => '#FFFFFF',
                'accent_color' => null,
                'background_color' => '#FFFFFF',
                'text_color' => '#000000',
                'min_plan_id' => 1,
                'category' => 'clasico',
                'created_at' => now(),
            ],
            
            // MARCAS (Disponibles desde plan CRECIMIENTO - min_plan_id: 2)
            [
                'name' => 'McDonald\'s',
                'slug' => 'mcdonalds',
                'primary_color' => '#DA291C',
                'secondary_color' => '#FFC72C',
                'accent_color' => null,
                'background_color' => '#FFFFFF',
                'text_color' => '#000000',
                'min_plan_id' => 2,
                'category' => 'marca',
                'created_at' => now(),
            ],
            [
                'name' => 'Starbucks',
                'slug' => 'starbucks',
                'primary_color' => '#00704A',
                'secondary_color' => '#FFFFFF',
                'accent_color' => null,
                'background_color' => '#FFFFFF',
                'text_color' => '#000000',
                'min_plan_id' => 2,
                'category' => 'marca',
                'created_at' => now(),
            ],
            [
                'name' => 'Home Depot',
                'slug' => 'home-depot',
                'primary_color' => '#F96302',
                'secondary_color' => '#FFFFFF',
                'accent_color' => null,
                'background_color' => '#FFFFFF',
                'text_color' => '#000000',
                'min_plan_id' => 2,
                'category' => 'marca',
                'created_at' => now(),
            ],
            [
                'name' => 'Pizza Hut',
                'slug' => 'pizza-hut',
                'primary_color' => '#EE3124',
                'secondary_color' => '#000000',
                'accent_color' => null,
                'background_color' => '#FFFFFF',
                'text_color' => '#000000',
                'min_plan_id' => 2,
                'category' => 'marca',
                'created_at' => now(),
            ],
            [
                'name' => 'Tech Blue',
                'slug' => 'tech-blue',
                'primary_color' => '#001F3F',
                'secondary_color' => '#00D9FF',
                'accent_color' => null,
                'background_color' => '#FFFFFF',
                'text_color' => '#000000',
                'min_plan_id' => 2,
                'category' => 'marca',
                'created_at' => now(),
            ],
            
            // ADICIONALES (Puedes agregar más aquí)
            [
                'name' => 'Sunset Rojo',
                'slug' => 'sunset-rojo',
                'primary_color' => '#FF4500',
                'secondary_color' => '#FFD700',
                'accent_color' => '#FF6347',
                'background_color' => '#FFFFFF',
                'text_color' => '#000000',
                'min_plan_id' => 1,
                'category' => 'clasico',
                'created_at' => now(),
            ],
            [
                'name' => 'Ocean Profundo',
                'slug' => 'ocean-profundo',
                'primary_color' => '#003366',
                'secondary_color' => '#66B2FF',
                'accent_color' => '#0099CC',
                'background_color' => '#FFFFFF',
                'text_color' => '#000000',
                'min_plan_id' => 1,
                'category' => 'clasico',
                'created_at' => now(),
            ],
            [
                'name' => 'Royal Purple',
                'slug' => 'royal-purple',
                'primary_color' => '#6A0DAD',
                'secondary_color' => '#FFD700',
                'accent_color' => '#9B30FF',
                'background_color' => '#FFFFFF',
                'text_color' => '#000000',
                'min_plan_id' => 2,
                'category' => 'marca',
                'created_at' => now(),
            ],
            [
                'name' => 'Forest Green',
                'slug' => 'forest-green',
                'primary_color' => '#228B22',
                'secondary_color' => '#8FBC8F',
                'accent_color' => '#006400',
                'background_color' => '#FFFFFF',
                'text_color' => '#000000',
                'min_plan_id' => 1,
                'category' => 'clasico',
                'created_at' => now(),
            ],
            [
                'name' => 'Midnight Dark',
                'slug' => 'midnight-dark',
                'primary_color' => '#1A1A1A',
                'secondary_color' => '#00D4FF',
                'accent_color' => '#FF00FF',
                'background_color' => '#0D0D0D',
                'text_color' => '#FFFFFF',
                'min_plan_id' => 2,
                'category' => 'marca',
                'created_at' => now(),
            ],
            [
                'name' => 'Tropical Vibes',
                'slug' => 'tropical-vibes',
                'primary_color' => '#FF6B9D',
                'secondary_color' => '#FEC601',
                'accent_color' => '#00CED1',
                'background_color' => '#FFFFFF',
                'text_color' => '#000000',
                'min_plan_id' => 1,
                'category' => 'clasico',
                'created_at' => now(),
            ],
            [
                'name' => 'Coral Reef',
                'slug' => 'coral-reef',
                'primary_color' => '#FF7F50',
                'secondary_color' => '#40E0D0',
                'accent_color' => '#FA8072',
                'background_color' => '#FFFFFF',
                'text_color' => '#000000',
                'min_plan_id' => 1,
                'category' => 'clasico',
                'created_at' => now(),
            ],
            [
                'name' => 'Mint Fresh',
                'slug' => 'mint-fresh',
                'primary_color' => '#00C9A7',
                'secondary_color' => '#98FF98',
                'accent_color' => '#00FA9A',
                'background_color' => '#FFFFFF',
                'text_color' => '#000000',
                'min_plan_id' => 1,
                'category' => 'clasico',
                'created_at' => now(),
            ],
            [
                'name' => 'Autumn Gold',
                'slug' => 'autumn-gold',
                'primary_color' => '#B8860B',
                'secondary_color' => '#DAA520',
                'accent_color' => '#CD853F',
                'background_color' => '#FFFFFF',
                'text_color' => '#000000',
                'min_plan_id' => 1,
                'category' => 'clasico',
                'created_at' => now(),
            ],
            [
                'name' => 'Cyber Neon',
                'slug' => 'cyber-neon',
                'primary_color' => '#39FF14',
                'secondary_color' => '#FF10F0',
                'accent_color' => '#00FFFF',
                'background_color' => '#0A0A0A',
                'text_color' => '#FFFFFF',
                'min_plan_id' => 2,
                'category' => 'marca',
                'created_at' => now(),
            ],
        ];
        
        DB::table('color_palettes')->insert($palettes);
    }
}
